### ISSUE TITLE
Getting windows by regex or if the title contains the argument string?

### ISSUE THREAD

**Issue by LeonT-A** [spyoungtech/ahk#108]
I've been trying to get a window who's title always ends in ` - VIM`, however I'm not having much luck. The first part of the window title is always changing, so I don't have a consistent name to search.

Is there a way to use regex to search for the window title or return a match if the title contains the string at all?

Something like `find_window(title=' - VIM', contains=True)`

**Comment by spyoungtech** [comment]
By default, [matches are not strict](https://github.com/spyoungtech/ahk/blob/master/ahk/window.py#L603-L613) (`exact=False` by default). By default, the `in` operator is used to match anywhere in a string. If you use `exact=True`, then `==` is used. If the value appears in the attribute at all, it will be found.

One important thing is that titles are represented as _bytes_ (mainly because window titles can be non-unicode). So you should use `find_window(title=b'foo')` for example. 

```python
ahk.find_window(title=b' VIM')
```

You can also pass in your own custom functions to find windows. The function will be called with the window object, if the function returns `True` it's included in the `find_window[s]` result.

```python
def my_special_window(win):
    if b'VIM' in win.title:
        return True
ahk.find_window(func=my_special_window)
```

**Comment by LeonT-A** [comment]
Thanks for the explanation and a solution on how to use regex. I didn't realize the title had to be in binary. It works as expected, thanks a bunch!
