### ISSUE TITLE
How to use cursor hover options?

### ISSUE THREAD

**Issue by emersonjr** [spyoungtech/ahk#114]
I basically would like to move mouse to some position and hover there for like 1 or 2 seconds, if a little tooltip shows up, which would indicate that that position has something clickable, then double click it. Otherwise, just stop doing anything.

How can I do that?

**Comment by spyoungtech** [comment]
Hmm. I'm not sure exactly how you might achieve this.

[This thread](https://autohotkey.com/board/topic/53672-get-the-text-content-of-a-tool-tip-window/://autohotkey.com/board/topic/53672-get-the-text-content-of-a-tool-tip-window/?&st=0) may help. 

If you can find some AHK code that works for you, I might be able to help translate it into the wrapper.

But in general, you can also run AHK code directly using the `run_script` method, so that might work for you with the code snippets in that thread.

**Comment by spyoungtech** [comment]
Closing for now, if you still need help on this @emersonjr let me know.
