### ISSUE TITLE
doc file needed and is there any way to use  control related function like controlsend, controlset/get text? 

### ISSUE THREAD

**Issue by woshichuanqilz** [spyoungtech/ahk#125]
as the title said, I check the source code seems not.

**Comment by spyoungtech** [comment]
Hi @woshichuanqilz  many of the control functions are [not yet implemented](https://github.com/spyoungtech/ahk/blob/master/ahk/window.py#L17-L92) at the moment, like I think you have found. This feature is tracked in #24  

It's been on the back burner mostly because I'm not sure how they are used. I think they are usually (always?) used as features to control windows, but I'm not sure. So, I may need some help implementing this functionality or at least understanding the use cases.

However, some features like `ControlSend`/`ControlClick` are used indirectly as part of the `window` module.

```python
win = ahk.find_window(title=b'Untitled - Notepad') # or any other window
win.send('hello')  # This uses `ControlSend` under the hood.
win.click(x=100, y=100) # This uses `ControlClick` under the hood
```

Hope that helps. If you have some use cases for control features, feel free to comment in #24
