### ISSUE TITLE
send does not reliably output to application

### ISSUE THREAD

**Issue by nnako** [spyoungtech/ahk#214]
I have the impression that the intended inputs which get flushed into a window by using `send()`, `type()` or `send_input()` functions, sometimes don't get flushed completely. or that some other effect "sometimes" is visible. I don't know the reason for this behavior.

Please have a look at the attached video (and excuse my bad English):

https://github.com/spyoungtech/ahk/assets/5845602/ef5333fc-7f1d-4193-bbde-7603c963eab0

**Comment by spyoungtech** [comment]
I think this might just be a case of how the application's window handle responds to events sent with AHK's `ControlSend` (ultimately, what is called when `win.send` is used.) The events are sent to the window handle, but the application may not actually do exactly what you want in this case. For example, an application may have several controls and may only respond when events are sent to a specific control within the application (as opposed to the main window handle). There could also be other behaviors of the application that results in the unexpected result; it's difficult to say without knowledge of how the application is programmed.

This method of sending events to windows using `ControlSend` bypasses how keyboard events normally reach an application or controls within an application, so it can sometimes be tricky to predict how the application will behave and some trial and error may be involved.  
In contrast, when using `ahk.send`, the events will be sent just as if the events came from the keyboard and the events will propagate to the appropriate applications/controls normally, which probably is why you get the expected behavior in this case.

Ultimately, I think this issue boils down to how the application is programmed to respond to events in different scenarios. I'm not sure why this works as expected in your application with F6 in your one hotkey, but not with sending the text followed by F7 in the other hotkey. But I am not able to replicate this using other programs, like `Notepad`.

For example, this code works as expected with `Notepad` reliably all the time:

```python
from ahk import AHK
ahk = AHK()
def callback():
    win = ahk.active_window
    assert 'Notepad' in win.title, f'this is expected active window to be a Notepad window. Got: {win.title!r}'
    win.send('__TEST__')
    win.send('{F5}') # in Notepad, pressing F5 will append a timestamp to the text window

# Use Win+N to trigger this callback 
ahk.add_hotkey('#n', callback=callback)

ahk.start_hotkeys()

ahk.block_forever() # sleeps in a loop forever; to prevent the script from exiting early.
```

So, I am not sure I am able to identify a specific problem on the side of AutoHotkey or the Python wrapper. If you're able to reproduce this issue in a common program (ideally one included with Windows) maybe I can help investigate further.

-----

It's unrelated to the problem you've demonstrated here, but it may be worth noting that in the current version (1.1.3) of `ahk`, there is a known issue surrounding concurrent access to the AHK daemon (for example if you invoke `ahk` methods in a thread, like what happens in hotkey callbacks). This was fixed in #209 but has not yet been published to PyPI.

**Comment by nnako** [comment]
@spyoungtech thanks for your great explanations. let me try to dig into it a bit further...

> I think this might just be a case of how the application's window handle responds to events sent with AHK's ControlSend (ultimately, what is called when win.send is used.) The events are sent to the window handle, but the application may not actually do exactly what you want in this case. For example, an application may have several controls and may only respond when events are sent to a specific control within the application (as opposed to the main window handle).

this would be strange, indeed. I deliberately tried set the focus to the intended control (element within the editor pane) by clicking around before hitting the specific hotkey. So, it seems that `win = ahk.active_window()` neutralizes my manual focus and goes "back" to the window (one step above the specific pane / element). If that is the case for my specific application "[Freeplane](https://docs.freeplane.org/)" (a mindmap editor), then I would be better off to try focusing on using `ahk.send()` as it seems to more successfully keep the current focus.

Is there, maybe, a way to select not only a window but rather a more detailed scope like a pane or other controls? Using `ahk`?

> This method of sending events to windows using ControlSend bypasses how keyboard events normally reach an application or controls within an application, so it can sometimes be tricky to predict how the application will behave and some trial and error may be involved.

I will try everything necessary to eventually make it right for each specific application. But I don't think I already know all the different ways to try this and that. Maybe even additional `<CR>` or other dummy keys would help in some cases.

> In contrast, when using ahk.send, the events will be sent just as if the events came from the keyboard and the events will propagate to the appropriate applications/controls normally, which probably is why you get the expected behavior in this case.

Yes, I think so. But still odd that it does not work always. But sometimes just partially or even not at all. Tricky with Freeplane and maybe many other applications...

> For example, this code works as expected with Notepad reliably all the time

I tried it with Notepad++ . When using `win = ahk.active_window` and then `win.send( ... )` there is no output on the desired tab. But when using `ahk.send( ... )`, the output **reliably** gets on the selected tab. Which is great.

**Comment by nnako** [comment]
I've made another test with the "more complex" application Freeplane.

https://github.com/spyoungtech/ahk/assets/5845602/b45c09bd-2b23-42a1-865b-ffb610659213

so, for this simple example, the issue would be solved by adding a "small" time delay within the callback, before starting to write characters into the application's buffer.

**Comment by nnako** [comment]
problem can be solved by avoiding `ahk.active_window` and adding some time delay within the callback before actually sending keys to the respective window.
