### ISSUE TITLE
Missing `NoEnv` and `SingleInstance` since 1.0.0?

### ISSUE THREAD

**Issue by manokara** [spyoungtech/ahk#222]
At some point, `main` diverged from the history at the `v0.14.2` tag and some directives that used to be in the package don't exist anymore, because `ahk/directives.py` in `main` was created in 31773fd without them. I noticed this because a script I run often used an older version on a certain machine, and when using it in another machine with the latest version it started complaining about missing directives. `NoEnv` and `SingleInstance` in particular. Is it correct to assume that such directives are no longer necessary because version 1.x assumes `NoEnv` and `SingleInstance`? Or do I have to use `run_script` to use them?

**Comment by spyoungtech** [comment]
Hi @manokara thanks for bringing this up.

> Is it correct to assume that such directives are no longer necessary because version 1.x assumes 

 That's pretty much correct -- `NoEnv` and `SingleInstance` are not present as options because they are [hard-coded](https://github.com/spyoungtech/ahk/blob/659fbb1410b3ddd25677e12cee85bc2bce501719/ahk/templates/daemon.ahk#L3C1-L5C20) into the daemon script.

Though breaking changes are expected between major versions, I'm not sure it was 100% intentional or, at least could have been more well-thought out, from a backwards-compatibility perspective to remove the directive classes entirely. In hindsight, I probably should have kept the directive classes, but just emit a warning that they have no effect in v1 if someone tries to use them.

**Comment by manokara** [comment]
Oh, indeed. Thanks for the quick response! I think I searched for `NoEnv` on GitHub but it didn't show the daemon script, otherwise I would've understood. 

> I probably should have kept the directive classes, but just emit a warning that they have no effect in v1 if someone tries to use them.

Yeah, I think it's too late now. Perhaps a migration guide could be added in the docs to help people upgrading from 0.x? Not only documenting the directives but also API changes.

**Comment by spyoungtech** [comment]
Yeah, the [v1 release notes](https://github.com/spyoungtech/ahk/releases/tag/v1.0.0) are probably the closest thing to cover most of the changes between v0.x and v1, but this is one that was overlooked. There's likely a number of other changes not explicitly called out, since the source code was pretty much entirely rewritten for v1.
