### ISSUE TITLE
Reason why `Control.get_text` uses `self.control_class` rather than `self.hwnd`?

### ISSUE THREAD

**Issue by ssweber** [spyoungtech/ahk#230]
Is there a reason that the `get_text` in `Control` is hard-coded to use the control_class rather than `hwnd`?

For example, Quickbooks desktop, all the input widgets are class “MauiFrame”.

I've worked around it by doing:

```
class ExtendedControl(Control):
    def get_text(self, blocking: bool = True):
        return self._engine.control_get_text(
            control=self.hwnd, # Changed from self.control_class
            title=f'ahk_id {self.window._ahk_id}',
            blocking=blocking,
            detect_hidden_windows=True,
            title_match_mode=(1, 'Fast'),
        )

_Originally posted by @ssweber in https://github.com/spyoungtech/ahk/issues/229#issuecomment-1688515261_

**Comment by spyoungtech** [comment]
It's possible this is a bug/oversight in the method. I don't believe I have any unittests currently covering this method. Controls are probably one of the weaker areas, mainly because I don't have much experience working with Controls in AHK myself, personally. 

I imagine the same issue probably exists for all the other methods (like `send`), too, in cases where the control class is not unique.

Though, I think I tried using `self.hwnd` and for some reason it did not work when testing `send`. But I will investigate this a little closer and see if I can come up with something.

**Comment by ssweber** [comment]
Thanks! I’m reworking a script right now, so I hope I can help flesh it out a bit. Using your py ahk is making it sooo much nicer to refactor
