### ISSUE TITLE
Why is window.id a string?

### ISSUE THREAD

**Issue by michaelmesser** [spyoungtech/ahk#269]
I would expect it to be an int.

**Comment by spyoungtech** [comment]
Hi @michaelmesser thanks for the question.

It may not be a satisfying answer, but the type is a `str` mostly for arbitrary and historical reasons (the internal APIs of the library use strings to communicate to/from AHK exclusively) and there hasn't been a compelling reason to introduce a potentially-breaking change to make it an `int` or anything else instead. Specifically, because window handles aren't really used in the same way as integers anyhow, I'm not sure users would benefit from such a change. That is to say: I don't think there is any case where you would do integer arithmetic, like add/subtract/divide on a window handle.

It's perhaps arguable `int` would be a _more correct_ type to use as opposed to `str` and, if we didn't care about backwards compatibility, it may be more reasonable to use `int` instead of `str`.  In a perfectly pedantic world, `window.id` (and other uses of window handles) would probably use a Python type that reflects the [HWND type](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types#HWND) (an alias for `HANDLE`, which is an alias for `PVOID`) from the underlying Windows APIs, as pywin32 does with its [PyHandle type](https://timgolden.me.uk/pywin32-docs/PyHANDLE.html), since HWND pointers are meant to be opaque pointers, as the underlying `PVOID` type definition implies.

But for now, I think the string probably serves just as well for its intended purposes and, in absence of a compelling use-case behind such a change, I would lean in favor of preserving compatibility than making the change for correctness sake alone.

**Comment by michaelmesser** [comment]
AHKv2 says `WinGetID` returns an integer. https://www.autohotkey.com/docs/v2/lib/WinGetID.htm Also https://learn.microsoft.com/en-us/dotnet/api/envdte.window.hwnd?view=visualstudiosdk-2022#envdte-window-hwnd uses int for the hwnd as well.

**Comment by spyoungtech** [comment]
Yeah. In AutoHotkey v1, HWNDs are [assigned as strings](https://github.com/AutoHotkey/AutoHotkey/blob/0b75f1176901ef7f2464f8aa9d6298d6bed11661/source/var.cpp#L26-L35). In V2, it just takes the HWND pointer and [casts it to an integer](https://github.com/AutoHotkey/AutoHotkey/blob/2a836cf2815ec947f70b18df3b79699a9dcf92e9/source/var.cpp#L29-L32). You can read more [about that here](https://www.autohotkey.com/boards/viewtopic.php?style=19&t=89745). In the referenced C++ code, `HWND` refers to a `HANDLE`, which is a `PVOID` type, as [documented here](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types#HWND).

So, yes, it's true AutoHotkey v2 returns an integer. There are also some other inconsistencies like this that exist. Something to keep in mind is that most of the methods in this library were written before AHK v2 was released. Also, this library supports both versions of AutoHotkey simultaneously. So, when such differences between AHKv1 and AHKv2 arise, the library has a decision to make and, in the case of return types, it tends to not consider what AHKv2 does and favor interoperability of the Python API between AutoHotkey versions and backwards compatiblity with previous versions of this library (written originally for v1 only) and thusly, return types will usually have the v1 behavior for purpose of backwards compatibility.

The Python API could just as easily smooth this difference over in the other direction and always cast to an integer, like the V2 behavior, but it just so happens that the v1 behavior was implemented first and did not cast the hexadecimal string to an int, and changing this now would be a potentially breaking change. Because of this, the Python return value will likely stay a string, at least until the next major version of this library, unless there's some compelling reason to change it sooner.

> [visualstudiosdk-2022#envdte-window-hwnd](https://learn.microsoft.com/en-us/dotnet/api/envdte.window.hwnd?view=visualstudiosdk-2022#envdte-window-hwnd) uses int for the hwnd as well.

That appears to be the .NET API for a class within a Visual Studio DLL. That's not quite the same thing as `HWND` in the win32 sense, as found in the Win32 [`GetWindow` function](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindow), or other APIs used by AutoHotkey. So what a class within Visual Studio's .NET API does probably doesn't have much bearing on what this library should do.


Hope that helps explain things.

**Comment by michaelmesser** [comment]
The explanation the this library provides an AHKv1 Python API to AHKv1 and AHKv2 makes sense.

> That's not quite the same thing as HWND in the win32 sense, as found in the Win32 [GetWindow function](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindow), or other APIs used by AutoHotkey.

Are they not the same? I was able to match the Visual Studio hwnd to an AHK id to find the AHK window of a Visual Studio solution.

**Comment by spyoungtech** [comment]
Glad that helps explain it. 

And yeah, they represent the same thing, but are different types. Pointers can be converted to integers and vice-versa, though there are problems with that approach, as the maintainer of AutoHotkey [pointed out in the link shared above](https://www.autohotkey.com/boards/viewtopic.php?style=19&t=89745) and [discussed briefly here](https://groups.google.com/g/jna-users/c/XGIwLUxwHBQ?pli=1). But it's a small distinction, I suppose 🤷‍♂️
