### ISSUE TITLE
How to Communicating data from Python to AHK

### ISSUE THREAD

**Issue by YesHub** [spyoungtech/ahk#80]
Use run_script(), ahk can Communicating data with python, how to python Communicating data with ahk snippet?

**Comment by spyoungtech** [comment]
The only data that gets sent from Python to AHK is the script itself. I'm not sure what else you might want to send to ahk other than the script.

@YesHub Can you give an example of what you want to accomplish? or an ahk script you want to use this way?

**Comment by YesHub** [comment]
There is no actual example, But it will be used in the future.
Like python code with sys.argv, Like ahk code with A_Args %1%%2%..., Passing Command Line Parameters to a Script.

**Comment by spyoungtech** [comment]
Okay, I understand now.

Right now, this packages does not have a way to directly provide additional args to a script like that.
I'll look into adding support for this use case!

You might be able to just change your AHK as a Python string a little bit to do something similar.

For example, suppose you have an ahk script like so that you would call like 

```autohotkey
msgbox %1% %2% %3% 
```

Instead of passing in args for this script, you could make your script a string with Python placeholders to use with `.format` and just make the script on-the-fly.

```python
from ahk import AHK
ahk = AHK()
script_template = "msgbox {:1} {:2} {:3}"
args = ['Blue', 'Green', "C:\\Test"]
script = script_template.format(*args)
ahk.run_script(script)
```

![image](https://user-images.githubusercontent.com/15212758/80274723-586ade00-8691-11ea-9668-6b7b101bb6ce.png)

**Comment by YesHub** [comment]
Great! Thank you so much.
