### ISSUE TITLE
Image_search - ValueError: malformed node or string: None

### ISSUE THREAD

**Issue by Rahul8498** [spyoungtech/ahk#84]
File "c:/Users/rrajpuro/Documents/Macros/test.py", line 6, in run
    ac.image_search("C:\\Users\\rrajpuro\\Pictures\\War.JPG")
  File "C:\Users\rrajpuro\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ahk\screen.py", line 74, in image_search
    return ast.literal_eval(resp)
  File "C:\Users\rrajpuro\AppData\Local\Programs\Python\Python37-32\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\rrajpuro\AppData\Local\Programs\Python\Python37-32\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "C:\Users\rrajpuro\AppData\Local\Programs\Python\Python37-32\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "C:\Users\rrajpuro\AppData\Local\Programs\Python\Python37-32\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: None

**Comment by spyoungtech** [comment]
Thanks for the report @Rahul8498 -- It looks like there's an issue when trying to use `image_search` from an ActionChain.

**Comment by Rahul8498** [comment]
Is there any work around for now?

**Comment by spyoungtech** [comment]
Not yet. If you wanted to address the issue yourself, you should be able to override the `image_search` method in an ActionChain subclass if you wanted to implement a way around this yourself.

I haven't had time to look into this just yet. Though, I think getting this to work in a reasonable way may take some time and probably relies on some additional tooling that doesn't exist yet.

One of the big challenges is utilizing any functions that return a value. It's pretty easy to put things like `mouse_move` or `send` into an action chain, because there's no return value to worry about. With things like `find_window` or `image_search` you'd need to build in some kind of objects that represent the _eventual_ value those will return in the generated AHK script.

There might be other shortcuts for simple usages of functions that return value. Basically the idea would be to bake in all the actions you plan to do with that return value and create a dedicated function for it. 

For example, suppose you look for an image just to click on it, you could make a new method in action chain called `find_image_and_click` that does not require any return value to operate.


```
class MyActionChain(ActionChain):
    def find_image_and_click(self, image_path):
        script = f"""Some AHK script that will find {image_path} and click it"""
        self.run_script(script)
```

**Comment by Rahul8498** [comment]
Thanks a lot for the suggestion. Also, it seems to be a very good approach which I should have implemeted. Will work on it right away!!
