### ISSUE TITLE
Could the `screenWidth` and `screenHeight` fields be exposed? 

### ISSUE THREAD

**Issue by lesterfan** [spyoungtech/ahk#85]
My use case involves resizing a window to a fraction of the current screen's dimensions. To this end, It would be nice to have the `screenWidth` and `screenHeight` fields exposed from the `screen` API.

**Comment by spyoungtech** [comment]
I'd be happy to look into adding this functionality. 

@lesterfan could you help me by pointing to the AHK docs for this or an example AHK script?

Would adding [SysGet](https://www.autohotkey.com/docs/commands/SysGet.htm#Monitor) functionality work for your case?

**Comment by idbrii** [comment]
[A_ScreenWidth/Height](https://www.autohotkey.com/docs/Variables.htm#Screen) gives you the dimensions of the primary monitor, but to get other monitors or the entire desktop (spanning monitors), you need to use [SysGet](https://www.autohotkey.com/docs/commands/SysGet.htm). SysGet covers more use cases, so it'd be preferable to me!

In my AutoHotkey scripts, I use SysGet to [find the active monitor](https://autohotkey.com/board/topic/85457-detecting-the-screen-the-current-window-is-on/), position windows at edges of monitors, and change layout based on the number of monitors and which is primary. (So I use Monitor MonitorCount MonitorPrimary and MonitorWorkArea.)

**Comment by lesterfan** [comment]
SysGet functionality would be perfect! 

Additionally, getting a handle to the active monitor like in @idbrii's case seems to be a really common use case which is not easy to implement. Having an API call specifically for that would be amazing, but I'm not sure if that's within the scope of this library.

**Comment by spyoungtech** [comment]
Thanks for the feedback on this and use cases.  I think my next step will be to implement `SysGet`. Might get around to that this weekend or the next.

I'll also invest some thought into what kind of utility will be provided around working with (multiple) monitors. 

I imagine having at least one high level function that would return some data structure or object with info of all monitors.


Maybe a mockup of what I'm thinking:
```py
>>> ahk.monitors
{1: {'primary': True, 'working_area': [0, 0, 3840, 2060], 'area': [0, 0, 3840, 2160]},
 2: {'primary': False, ...}
...
}
```

```py
>>> ahk.primary_monitor
{'working_area': [0, 0, 3840, 2060], 'area': [0, 0, 3840, 2160]}
```

Or maybe a full on class for representing a monitor

```py
>>> mon= ahk.primary_monitor
>>> mon.area
[0, 0, 3840, 2160]
>>> mon.working_area
[0, 0, 3840, 2060]
>>> mon.number
1
```

**Comment by idbrii** [comment]
That sounds awesome!

My working solution is a [simple class and some hard-coded coordinates](https://github.com/idbrii/daveconfig/blob/master/win/autohotkey/ahk_david.py#L98-L119)

The x,y of a monitor may be negative, so having width/height is useful (or maybe mon.area *is* x,y,w,h and not x1,y1,x2,y2?). Having a class might be simpler than storing a bunch of derived data.

Also, exposing attributes that produce values easily applied to the existing API would help. Being able to do something like this would be great:

```python
mon = ahk.get_monitor_by_layout(0) # the left-most monitor
win = ahk.find_window_by_class("Vim")
x,y = mon.topleft
w,h = mon.dimensions
win.move(x,y, w/2,h)

win = ahk.find_window_by_exe("chrome.exe")
x,y = mon.topright
win.move(x - w/2,y, w/2,h)
```

The physical layout (determined by monitor pixel locations within the whole desktop) is more useful than monitor numbers. When I have three monitors, often my centre is 1 because it's the primary. Right now, my rightmost monitor is 1 but it's disabled and Windows won't let me remove it.

Regardless, getting access to those SysGet values is a great first step. Looking forward to it!

**Comment by h2023man** [comment]
**Subject:** Your Dream Job Awaits: Apply Now to Join GitHub as a Developer!

Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
ohJohanZ, @iAnonymous3000, @aurium, @kuya89898, @Imaniac230, @ekyonn, @sayha216, @belvikont, @ranjaniryan, @yanel, @chandpreet751, @Hexcolyte, @Taladral, @MustafaaCS, @ratte, @hhqq2211, @rickarubio, @initharrington, @Vvkmnn, @Staszek-org

**Comment by KyleTheScientist** [comment]
In the meantime, win32api has functionality for this:
```python
from win32api import GetMonitorInfo, EnumDisplayMonitors

class Monitor:
    pass

def get_monitors():
    monitors = []
    for m in EnumDisplayMonitors():
        info = GetMonitorInfo(m[0])
        monitor = Monitor()
        monitor.name = info['Device'],
        monitor.x = info['Work'][0],
        monitor.y = info['Work'][1],
        monitor.width = info['Work'][2],
        monitor.height = info['Work'][3],
        monitor.is_primary = info['Flags'] == 1
        monitors.append(monitor)

    return monitors
   ```

or more simply:

```python
from win32api import EnumDisplayMonitors

def get_monitors():
    return [m[0] for m in EnumDisplayMonitors()]
```

**Comment by spyoungtech** [comment]
For whatever it's worth, I finally had a personal use case for this and decided to make an attempt at enabling this functionality via the [ahk-wmutil](https://github.com/spyoungtech/ahk-wmutil/) extension package.

It seems to work well for my use case, but I haven't done extensive testing, since I only have my personal monitor setup to test against. But I use 3 monitors all with different resolutions and DPI settings and it seems to do the right thing.

In any case, I've decided that I'm going to try to keep the focus of the `ahk` package on, more or less, providing _just_ the APIs that are directly exposed by AutoHotkey. For other use cases and accessories, I will defer to community-provided extensions (see [extending docs](https://ahk.readthedocs.io/en/latest/extending.html)), examples in documentation , etc. in lieu of providing implementations like these directly.

In the near future, I hope to provide a dedicated space in the documentation for examples, so keep an eye out for that if that sounds like something you might wish to contribute.
