### ISSUE TITLE
[Question] Delay

### ISSUE THREAD

**Issue by samomar** [spyoungtech/ahk#91]
I have no ahk experience but I tried to use this as an alternative to pyinput and the `key_press` events are only sent once more or less, every second, is there a global variable to control the delay between actions?

**Comment by spyoungtech** [comment]
Hmm. 

> the `key_press` events are only sent once more or less, every second

To help me better understand this, could you please provide the relevant code you're using? I'd also like to better understand the behavior you're expecting/want vs. the behavior you're actually observing.


The `key_press` method itself does not expose a parameter for _delay_. This is because the underlying AHK functionality (`SendInput`) does not obey [`SetKeyDelay`](https://www.autohotkey.com/docs/commands/SetKeyDelay.htm)

> SetKeyDelay is not obeyed by SendInput; there is no delay between keystrokes [...]

So, when using `key_press` the events should fire pretty much immediately and without delay.

If you _want_ to add a delay, there are a number of other methods in the library that support setting a custom delay and could be made to give you the same effect as `key_press` while controlling the delay!
